#pragma once
#include "Recorces.h"
#include "Board.h"
#include"Non_moving.h"
#include"Moving.h"
#include"Regular_monster.h"
#include"Smart_monster.h"
#include"digger.h"
#include"Diamond.H"
#include"Stone.h"
#include"Wall.h"
#include"Toolbar.h"
#include"Level.h"
#include"Life.h"
#include"Score.h"
#include"gift.h"
#include"screen.h"
#include"StartScreen.h"
#include"background.h"
#include"StoneToolbar.h"
#include"gameover.h"
#include "Timer.h"
#include"levelScreen.h"
#include"GameSuccess.h"

using::sf::Clock;